-- CRIAR TABELA NOVA
USE sakila;
CREATE TABLE noticia(
	noticia_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100),
	historia VARCHAR(300)
);

-- ADICIONAR COLUNA EM TABELA
ALTER TABLE noticia ADD COLUMN data_postagem date NOT NULL;

-- MODIFICA TIPO E PROPRIEDADE DA COLUNA
ALTER TABLE noticia MODIFY noticia_id BIGINT;

-- ADD INCREMENTO AUTO
-- ESPECIFIQUE TIPO COLUNA + AUTO
ALTER TABLE noticia MODIFY noticia_id BIGINT auto_increment;

-- ALTERAR TIPO E NOME / COLUNA
ALTER TABLE noticia CHANGE historia conteudo_postagem VARCHAR(1000) NOT NULL;

-- DROPAR EXCLUIR COLUNA
ALTER TABLE noticia DROP COLUMN data_postagem;

-- ADD NOVA COLUNA APOS OUTRA
ALTER TABLE noticia ADD COLUMN data_postagem DATETIME NOT NULL AFTER titulo;


